// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMZaDYpHg5r5oQV-C8FNAr23e_Du64xTo',
    appId: '1:230126840117:web:10bab5043d8f8be049847c',
    messagingSenderId: '230126840117',
    projectId: 'noti-dust',
    authDomain: 'noti-dust.firebaseapp.com',
    storageBucket: 'noti-dust.appspot.com',
    measurementId: 'G-RSBT3XX3EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeFEeeJfVaGn3fuNj14ifl8Gw5QJ6oU50',
    appId: '1:230126840117:android:d00158b743fd35e849847c',
    messagingSenderId: '230126840117',
    projectId: 'noti-dust',
    storageBucket: 'noti-dust.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCepXs2kl8t7MoglCFf3wfAV_R1IqjHnys',
    appId: '1:230126840117:ios:29a2ea4c0a5417a849847c',
    messagingSenderId: '230126840117',
    projectId: 'noti-dust',
    storageBucket: 'noti-dust.appspot.com',
    androidClientId: '230126840117-1v1q9m6psj6ern77alte1onhask83tg2.apps.googleusercontent.com',
    iosClientId: '230126840117-nvgomssf5f2d47jdrtvt9028qlf3ja01.apps.googleusercontent.com',
    iosBundleId: 'com.example.notiDust',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCepXs2kl8t7MoglCFf3wfAV_R1IqjHnys',
    appId: '1:230126840117:ios:6e9ec9518670ea3549847c',
    messagingSenderId: '230126840117',
    projectId: 'noti-dust',
    storageBucket: 'noti-dust.appspot.com',
    androidClientId: '230126840117-1v1q9m6psj6ern77alte1onhask83tg2.apps.googleusercontent.com',
    iosClientId: '230126840117-3m6aiq8orttbaju4egqn3235b0aba03f.apps.googleusercontent.com',
    iosBundleId: 'com.example.notiDust.RunnerTests',
  );
}
